fasta_path: "/share/project/mieke/tax/5th_run_fully_unaligned_metaeuk/fully_unaligned_contigs.fasta"
gff_path: "/share/project/mieke/tax/5th_run_fully_unaligned_metaeuk/fully_unaligned_annotation.gff"
output_path: "./report/"
taxon_id: "38358"
extract_proteins: True
target_exclude: True
force: True
